# Generated by Django 5.2.4 on 2025-07-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Müvekkil'), ('provider', 'Avukat')], max_length=10, verbose_name='Kullanıcı Tipi'),
        ),
    ]
